FROM alpine:3.8 AS certificates

RUN apk add --no-cache bash
RUN apk add --no-cache curl

RUN apk update \
        && apk upgrade \
        && apk add --no-cache \
        ca-certificates \
        && update-ca-certificates 2>/dev/null || true

# Create a final distroless image
FROM gcr.io/distroless/base:latest AS distroless

COPY --from=certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY target/app /

CMD ["/app"]
