// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"
	api "coachify-account-api/models/api"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"

	models "coachify-account-api/models"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// Confirm provides a mock function with given fields: ctx, req
func (_m *AuthService) Confirm(ctx context.Context, req *api.ConfirmUserRequest) *models.ApiError {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, *api.ConfirmUserRequest) *models.ApiError); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ApiError)
		}
	}

	return r0
}

// ConfirmResetPassword provides a mock function with given fields: ctx, request
func (_m *AuthService) ConfirmResetPassword(ctx *gin.Context, request *api.ConfirmResetPasswordRequest) *models.ApiError {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmResetPassword")
	}

	var r0 *models.ApiError
	if rf, ok := ret.Get(0).(func(*gin.Context, *api.ConfirmResetPasswordRequest) *models.ApiError); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ApiError)
		}
	}

	return r0
}

// GetAllUsersPag provides a mock function with given fields: _a0
func (_m *AuthService) GetAllUsersPag(_a0 api.SearchUser) ([]*api.ApiUser, int, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersPag")
	}

	var r0 []*api.ApiUser
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(api.SearchUser) ([]*api.ApiUser, int, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(api.SearchUser) []*api.ApiUser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.ApiUser)
		}
	}

	if rf, ok := ret.Get(1).(func(api.SearchUser) int); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(api.SearchUser) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUserByExternalId provides a mock function with given fields: ctx, userId
func (_m *AuthService) GetUserByExternalId(ctx context.Context, userId string) (*api.ApiUser, *models.ApiError) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByExternalId")
	}

	var r0 *api.ApiUser
	var r1 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.ApiUser, *models.ApiError)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.ApiUser); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ApiUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *models.ApiError); ok {
		r1 = rf(ctx, userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.ApiError)
		}
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: ctx, userId
func (_m *AuthService) GetUserById(ctx context.Context, userId string) (*api.ApiUser, *models.ApiError) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *api.ApiUser
	var r1 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, string) (*api.ApiUser, *models.ApiError)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *api.ApiUser); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.ApiUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *models.ApiError); ok {
		r1 = rf(ctx, userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.ApiError)
		}
	}

	return r0, r1
}

// InitResetPassword provides a mock function with given fields: ctx, request
func (_m *AuthService) InitResetPassword(ctx context.Context, request *api.ResetPasswordRequest) *models.ApiError {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for InitResetPassword")
	}

	var r0 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, *api.ResetPasswordRequest) *models.ApiError); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ApiError)
		}
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, username, oldRefreshToken
func (_m *AuthService) RefreshToken(ctx context.Context, username string, oldRefreshToken string) (string, string, *models.ApiError) {
	ret := _m.Called(ctx, username, oldRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 string
	var r1 string
	var r2 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, *models.ApiError)); ok {
		return rf(ctx, username, oldRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, oldRefreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, username, oldRefreshToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) *models.ApiError); ok {
		r2 = rf(ctx, username, oldRefreshToken)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*models.ApiError)
		}
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: ctx, req
func (_m *AuthService) Register(ctx context.Context, req *api.CreateUserRequest) (*api.RegisterResponse, *models.ApiError) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *api.RegisterResponse
	var r1 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, *api.CreateUserRequest) (*api.RegisterResponse, *models.ApiError)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *api.CreateUserRequest) *api.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *api.CreateUserRequest) *models.ApiError); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.ApiError)
		}
	}

	return r0, r1
}

// ResendConfirmEmail provides a mock function with given fields: ctx, email
func (_m *AuthService) ResendConfirmEmail(ctx context.Context, email string) *models.ApiError {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ResendConfirmEmail")
	}

	var r0 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ApiError); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ApiError)
		}
	}

	return r0
}

// TryToConnect provides a mock function with given fields: ctx, request
func (_m *AuthService) TryToConnect(ctx context.Context, request api.LoginRequest) (*api.LoginResponse, *models.ApiError) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for TryToConnect")
	}

	var r0 *api.LoginResponse
	var r1 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, api.LoginRequest) (*api.LoginResponse, *models.ApiError)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, api.LoginRequest) *api.LoginResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, api.LoginRequest) *models.ApiError); ok {
		r1 = rf(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.ApiError)
		}
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, id, req
func (_m *AuthService) UpdateUser(ctx context.Context, id string, req *api.RequestUpdateUser) *models.ApiError {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *models.ApiError
	if rf, ok := ret.Get(0).(func(context.Context, string, *api.RequestUpdateUser) *models.ApiError); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ApiError)
		}
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
